site_name: PostgreSQL Notes
repo_url: https://github.com/tzelleke/postgres-notes
theme:
  name: material
  palette:
    scheme: default
    primary: lime
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences: # make exceptions to highlighting of code:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
plugins:
  - search:
  - mkdocstrings:
  - awesome-pages:
  - table-reader:
  - macros:
  - mermaid2:
      arguments:
        theme: 'light'
# TODO: serve from project
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
